

spring:
  datasource:
    url: jdbc:mysql://192.168.213.128:3306/oauth2db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 9999